services:
  rhs_dev.db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: rhs_dev.db
    environment:
      - ACCEPT_EULA: "Y"
      - SA_PASSWORD: "yourStrong(!)Password"
    ports:
      - "1433:1433"
    volumes:
      - ./.containers/db:/var/lib/mssql/data

  rhs.api:
    ports:
      - "5099:80"
      - "7258:443"
    image: ${DOCKER_REGISTRY-}rhsapi
    build:
      context: .
      dockerfile: ./RHS.API/Dockerfile
    environment:
      - "ASPNETCORE_ENVIRONMENT": "Development"
      - "ASPNETCORE_URLS": "https://+:7258;http://+:5099"
      #- "ASPNETCORE_HTTP_PORT": "5099"
      - "ASPNETCORE_Kestrel__Certificates__Default__Password": "eeJD2puyfUyYYPXfQt"
      - "ASPNETCORE_Kestrel__Certificates__Default__Path": "/https/aspnetapp.pfx"
      - "ConnectionStrings:Database": "Host=rhs_dev.db;Port=5432;Database=rhs_dev;Username=rhs_dev;Password=postgres;Include Error Detail=true"
    volumes:
      - ~/.aspnet/https:/https:ro
    depends_on:
      - rhs_dev.db