# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - RHSPortfolio

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/README.md'
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: 'RHSPortfolio' 
  #AZURE_WEBAPP_PACKAGE_PATH: './publish' 
  DOTNET_VERSION: '8.x'
  SOLUTION_PATH: './RHS.sln'
  API_PROJECT_PATH: './src/RHS.API/RHS.API.csproj'
  #PUBLISH_DIR: '${{ github.workspace }}/publish'
  PUBLISH_DIR: 'publish'
  TESTCONTAINERS_RYUK_DISABLED: true
  TESTCONTAINERS_CHECKS_DISABLE: true
  
jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
          
    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          
      - name: Install ICU libraries
        run: sudo apt-get update && sudo apt-get install -y libicu-dev

      - name: Docker Info (debug)
        run: docker info
                
      - name: Restore 
        run: dotnet restore ${{ env.SOLUTION_PATH }}

      - name: Clean
        run: dotnet clean ${{ env.SOLUTION_PATH }}
        
      - name: Build
        run: dotnet build ${{ env.SOLUTION_PATH }} --configuration Release --no-restore
        
      - name: Test
        env:
          ASPNETCORE_ENVIRONMENT: Testing
          TESTCONTAINERS_HOST_OVERRIDE: localhost
          DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 0
        run: dotnet test ${{ env.SOLUTION_PATH }} --configuration Release --no-restore --no-build --verbosity normal

      - name: Publish
        run: dotnet publish ${{ env.API_PROJECT_PATH }} --configuration Release --no-restore --no-build --output ${{ github.workspace }}/${{ env.PUBLISH_DIR }} --no-dependencies

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: webapp
          path: ${{ env.PUBLISH_DIR }}

  deploy:
    name: Deploy to Azure
    runs-on: ubuntu-latest
    needs: [build-and-test]

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: webapp
          path: ${{ env.PUBLISH_DIR }}

      - name: Deploy
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.PUBLISH_DIR }}
